from typing import Protocol
from uuid import UUID

from src.tenant.domain.entities import Tenant


class TenantRepository(Protocol):
    async def create(self, tenant: Tenant) -> Tenant: ...
    async def get_by_id(self, tenant_id: UUID) -> Tenant | None: ...
    async def get_by_cnpj(self, cnpj: str) -> Tenant | None: ...
    async def update(self, tenant: Tenant) -> Tenant: ...
