from typing import Protocol
from uuid import UUID

from src.templates.domain.entities import Template, TipoTemplate


class TemplateRepository(Protocol):
    async def create(self, template: Template) -> Template: ...
    async def get_by_id(self, id: UUID, tenant_id: UUID) -> Template | None: ...
    async def get_ativo_by_tipo(self, tenant_id: UUID, tipo: TipoTemplate) -> Template | None: ...
    async def list_by_tenant(self, tenant_id: UUID) -> list[Template]: ...
    async def update(self, template: Template) -> Template: ...
    async def delete(self, id: UUID, tenant_id: UUID) -> None: ...
