# Generated by Django 5.0.1 on 2026-01-23 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orcamentos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proposta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20, unique=True)),
                ('cpf_cnpj', models.CharField(max_length=18)),
                ('endereco_completo', models.CharField(max_length=255)),
                ('bairro', models.CharField(max_length=100)),
                ('cep', models.CharField(max_length=9)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('aceita', 'Aceita'), ('recusada', 'Recusada')], default='pendente', max_length=20)),
                ('data_criacao', models.DateField(auto_now_add=True)),
                ('data_aceite', models.DateField(blank=True, null=True)),
                ('dias_desde_aceite', models.IntegerField(default=0)),
                ('prazo_entrega', models.IntegerField(default=45)),
                ('prazo_vistoria', models.IntegerField(default=60)),
                ('prazo_monitoramento', models.IntegerField(default=90)),
                ('pdf_proposta', models.FileField(blank=True, null=True, upload_to='propostas/')),
                ('convertido_contrato', models.BooleanField(default=False)),
                ('orcamento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='proposta', to='orcamentos.orcamento')),
            ],
            options={
                'db_table': 'propostas',
                'ordering': ['-data_criacao'],
            },
        ),
    ]
