from typing import Protocol
from uuid import UUID

from src.premissas.domain.entities import Premissa


class PremissaRepository(Protocol):
    async def create(self, premissa: Premissa) -> Premissa: ...
    async def get_by_id(self, premissa_id: UUID) -> Premissa | None: ...
    async def get_ativa(self, tenant_id: UUID) -> Premissa | None: ...
    async def update(self, premissa: Premissa) -> Premissa: ...
