# Generated by Django 5.0.1 on 2026-01-23 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contratos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('telefone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('tipo', models.CharField(choices=[('vendedor', 'Vendedor'), ('indicacao', 'Indicação')], default='vendedor', max_length=20)),
                ('comissao_percentual', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('ativo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'vendedores',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='VendaVendedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_venda', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_comissao', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_venda', models.DateField()),
                ('data_pagamento', models.DateField(blank=True, null=True)),
                ('pago', models.BooleanField(default=False)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contratos.contrato')),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendas', to='vendedores.vendedor')),
            ],
            options={
                'db_table': 'vendas_vendedor',
                'ordering': ['-data_venda'],
            },
        ),
    ]
