# Generated by Django 5.0.1 on 2026-01-23 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Vendedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('telefone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('tipo', models.CharField(choices=[('vendedor', 'Vendedor'), ('indicacao', 'Indicação')], default='vendedor', max_length=20)),
                ('comissao_percentual', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('ativo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'vendedores',
                'ordering': ['nome'],
            },
        ),
    ]
