# Generated by Django 5.0.1 on 2026-01-23 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendedores', '0002_vendedor_bloqueado_vendedor_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendedor',
            name='comissao_percentual',
        ),
    ]
