# Generated by Django 5.0.1 on 2026-01-26 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0001_initial'),
        ('vendedores', '0003_remove_vendedor_comissao_percentual'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendaVendedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_venda', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_comissao', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_venda', models.DateField()),
                ('data_pagamento', models.DateField(blank=True, null=True)),
                ('pago', models.BooleanField(default=False)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contratos.contrato')),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendas', to='vendedores.vendedor')),
            ],
            options={
                'db_table': 'vendas_vendedor',
                'ordering': ['-data_venda'],
            },
        ),
    ]
