from typing import Protocol
from uuid import UUID

from src.auth.domain.entities import User


class UserRepository(Protocol):
    async def create(self, user: User) -> User: ...
    async def get_by_id(self, user_id: UUID) -> User | None: ...
    async def get_by_email(self, email: str, tenant_id: UUID) -> User | None: ...
    async def update(self, user: User) -> User: ...
