# Generated by Django 5.0.1 on 2026-01-23 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20, unique=True)),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('forma_pagamento', models.CharField(choices=[('vista', 'À Vista'), ('parcelado', 'Parcelado'), ('financiamento', 'Financiamento')], max_length=20)),
                ('numero_parcelas', models.IntegerField(default=1)),
                ('valor_parcela', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('data_assinatura', models.DateField(auto_now_add=True)),
                ('data_inicio_obra', models.DateField(blank=True, null=True)),
                ('data_conclusao', models.DateField(blank=True, null=True)),
                ('prazo_execucao_dias', models.IntegerField(default=45)),
                ('dias_ate_entrega', models.IntegerField(default=0)),
                ('dias_ate_vistoria', models.IntegerField(default=0)),
                ('dias_ate_monitoramento', models.IntegerField(default=0)),
                ('pdf_contrato', models.FileField(blank=True, null=True, upload_to='contratos/')),
                ('garantia_instalacao_meses', models.IntegerField(default=12)),
                ('garantia_placas_anos', models.IntegerField(default=25)),
                ('garantia_inversor_anos', models.IntegerField(default=10)),
                ('ativo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'contratos',
                'ordering': ['-data_assinatura'],
            },
        ),
    ]
