# Generated by Django 5.0.1 on 2026-01-26 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contratos', '0001_initial'),
        ('propostas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='proposta',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contrato', to='propostas.proposta'),
        ),
    ]
