# Generated by Django 5.0.1 on 2026-02-10 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contrato',
            name='dias_ate_entrega',
        ),
        migrations.RemoveField(
            model_name='contrato',
            name='dias_ate_monitoramento',
        ),
        migrations.RemoveField(
            model_name='contrato',
            name='dias_ate_vistoria',
        ),
        migrations.RemoveField(
            model_name='contrato',
            name='garantia_inversor_anos',
        ),
        migrations.RemoveField(
            model_name='contrato',
            name='garantia_placas_anos',
        ),
        migrations.AddField(
            model_name='contrato',
            name='banco_agencia',
            field=models.CharField(default='0903', max_length=10),
        ),
        migrations.AddField(
            model_name='contrato',
            name='banco_conta',
            field=models.CharField(default='50661-1', max_length=20),
        ),
        migrations.AddField(
            model_name='contrato',
            name='banco_nome',
            field=models.CharField(default='Banco Cooperativo Sicredi S.A.', max_length=100),
        ),
        migrations.AddField(
            model_name='contrato',
            name='banco_titular',
            field=models.CharField(default='38.068.450 Mateus Leonco Concato', max_length=255),
        ),
        migrations.AddField(
            model_name='contrato',
            name='descricao_pagamento',
            field=models.TextField(blank=True, default='', help_text='Descrição detalhada da forma de pagamento'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='empresa_cep',
            field=models.CharField(default='79890-270', max_length=9),
        ),
        migrations.AddField(
            model_name='contrato',
            name='empresa_cidade',
            field=models.CharField(default='Itaporã', max_length=100),
        ),
        migrations.AddField(
            model_name='contrato',
            name='empresa_cnpj',
            field=models.CharField(default='38.068.450/0001-99', max_length=18),
        ),
        migrations.AddField(
            model_name='contrato',
            name='empresa_endereco',
            field=models.CharField(default='Rua Maria Rosa, nº S/N, bairro Parque Ipanema', max_length=500),
        ),
        migrations.AddField(
            model_name='contrato',
            name='empresa_estado',
            field=models.CharField(default='MS', max_length=2),
        ),
        migrations.AddField(
            model_name='contrato',
            name='empresa_razao_social',
            field=models.CharField(default='MAB ENERGIA SOLAR', max_length=255),
        ),
        migrations.AddField(
            model_name='contrato',
            name='empresa_representante_cpf',
            field=models.CharField(default='051.536.511-42', max_length=14),
        ),
        migrations.AddField(
            model_name='contrato',
            name='empresa_representante_nome',
            field=models.CharField(default='Mateus Leonço Concato', max_length=255),
        ),
        migrations.AddField(
            model_name='contrato',
            name='empresa_representante_rg',
            field=models.CharField(default='001939969', max_length=20),
        ),
        migrations.AddField(
            model_name='contrato',
            name='foro_comarca',
            field=models.CharField(default='Itaporã/MS', max_length=100),
        ),
        migrations.AddField(
            model_name='contrato',
            name='valor_parcela_extenso',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='contrato',
            name='valor_total_extenso',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='data_assinatura',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='forma_pagamento',
            field=models.CharField(choices=[('vista', 'À Vista'), ('cartao', 'Cartão de Crédito'), ('financiamento', 'Financiamento Bancário')], max_length=20),
        ),
    ]
