# Generated by Django 5.0.1 on 2026-02-02 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='tipo',
            field=models.CharField(choices=[('orcamento', 'Orçamento'), ('contrato', 'Contrato')], max_length=20),
        ),
    ]
