from typing import Protocol
from uuid import UUID

from src.vendedores.domain.entities import VendaVendedor


class VendaVendedorRepository(Protocol):
    async def create(self, venda: VendaVendedor) -> VendaVendedor: ...
    async def get_by_contrato(self, contrato_id: UUID, tenant_id: UUID) -> VendaVendedor | None: ...
    async def list_by_vendedor(self, vendedor_id: UUID, tenant_id: UUID) -> list[VendaVendedor]: ...
    async def marcar_pago(self, venda_id: UUID, tenant_id: UUID) -> VendaVendedor | None: ...
