from typing import Protocol
from uuid import UUID

from src.equipamentos.domain.entities import Inversor, Painel


class PainelRepository(Protocol):
    async def create(self, painel: Painel) -> Painel: ...
    async def get_by_id(self, painel_id: UUID, tenant_id: UUID) -> Painel | None: ...
    async def list_ativos(self, tenant_id: UUID) -> list[Painel]: ...
    async def update(self, painel: Painel) -> Painel: ...


class InversorRepository(Protocol):
    async def create(self, inversor: Inversor) -> Inversor: ...
    async def get_by_id(self, inversor_id: UUID, tenant_id: UUID) -> Inversor | None: ...
    async def list_ativos(self, tenant_id: UUID) -> list[Inversor]: ...
    async def update(self, inversor: Inversor) -> Inversor: ...
