# Generated by Django 5.0.1 on 2026-01-23 20:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
        ('vendedores', '0002_vendedor_bloqueado_vendedor_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='vendedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clientes', to='vendedores.vendedor'),
        ),
    ]
