# Generated by Django 5.0.1 on 2026-01-23 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('kit', 'Kit'), ('servicos', 'Serviços'), ('custos', 'Custos')], max_length=20)),
                ('item', models.CharField(max_length=255)),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('quantidade', models.IntegerField(default=0)),
                ('custo_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('custo_total', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('descricao', models.TextField(blank=True)),
                ('ativo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'equipamentos',
                'ordering': ['categoria', 'item'],
            },
        ),
    ]
