# Generated by Django 5.0.1 on 2026-01-23 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipamentos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inversor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=100)),
                ('fabricante', models.CharField(max_length=100)),
                ('potencia_w', models.IntegerField(help_text='Potência nominal em Watts')),
                ('potencia_maxima_w', models.IntegerField(help_text='Potência máxima suportada')),
                ('preco_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ativo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'inversores',
                'ordering': ['potencia_w'],
            },
        ),
        migrations.CreateModel(
            name='Painel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=100)),
                ('fabricante', models.CharField(max_length=100)),
                ('potencia_w', models.IntegerField(help_text='Potência em Watts')),
                ('area_m2', models.DecimalField(decimal_places=2, default=2.5, max_digits=5)),
                ('eficiencia', models.DecimalField(decimal_places=2, default=0.21, help_text='Ex: 0.21 = 21%', max_digits=5)),
                ('preco_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ativo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'paineis',
                'ordering': ['-potencia_w'],
            },
        ),
    ]
