# Generated by Django 5.0.1 on 2026-01-23 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipamentos', '0002_inversor_painel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inversor',
            name='preco_unitario',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='painel',
            name='preco_unitario',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
