# Generated by Django 5.0.1 on 2026-01-26 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipamentos', '0009_atualizar_paineis'),
    ]

    operations = [
        migrations.AddField(
            model_name='inversor',
            name='overload',
            field=models.DecimalField(choices=[(0.5, '50%'), (0.6, '60%'), (0.7, '70%'), (0.8, '80%')], decimal_places=2, default=0.7, help_text='Capacidade de overload', max_digits=3),
        ),
    ]
