# Generated by Django 5.0.1 on 2026-01-23 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Premissa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imposto_percentual', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('comissao_percentual', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('lucro_percentual', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('montagem_por_painel', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('valor_projeto', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('taxa_inflacao_anual', models.DecimalField(decimal_places=2, default=9.5, max_digits=5)),
                ('perda_eficiencia_sistema', models.DecimalField(decimal_places=2, default=0.8, max_digits=5)),
                ('tempo_vida_minima', models.IntegerField(default=25)),
                ('validade_proposta_dias', models.IntegerField(default=10)),
                ('ativo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'premissas',
                'ordering': ['-created_at'],
            },
        ),
    ]
