# Generated by Django 5.0.1 on 2026-01-23 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('premissas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='premissa',
            name='lucro_percentual',
        ),
        migrations.RemoveField(
            model_name='premissa',
            name='perda_eficiencia_sistema',
        ),
        migrations.AddField(
            model_name='premissa',
            name='garantia_instalacao_meses',
            field=models.IntegerField(default=12),
        ),
        migrations.AddField(
            model_name='premissa',
            name='hsp_padrao',
            field=models.FloatField(default=4.85, help_text='Horas de Sol Pico padrão'),
        ),
        migrations.AddField(
            model_name='premissa',
            name='margem_lucro_percentual',
            field=models.FloatField(default=30.0, help_text='Margem de lucro padrão (%)'),
        ),
        migrations.AddField(
            model_name='premissa',
            name='overload_inversor',
            field=models.FloatField(default=0.75, help_text='Fator de overload do inversor'),
        ),
        migrations.AddField(
            model_name='premissa',
            name='perda_padrao',
            field=models.FloatField(default=0.2, help_text='Perda padrão do sistema (0.20 = 20%)'),
        ),
        migrations.AddField(
            model_name='premissa',
            name='prazo_entrega_dias',
            field=models.IntegerField(default=45),
        ),
        migrations.AddField(
            model_name='premissa',
            name='taxa_juros_maquininha',
            field=models.JSONField(default=dict, help_text="Ex: {'12': 10.5, '18': 18.3}"),
        ),
    ]
