# Generated by Django 5.0.1 on 2026-01-23 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('premissas', '0002_remove_premissa_lucro_percentual_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='premissa',
            name='prazo_entrega_dias',
        ),
        migrations.RemoveField(
            model_name='premissa',
            name='taxa_inflacao_anual',
        ),
        migrations.RemoveField(
            model_name='premissa',
            name='taxa_juros_maquininha',
        ),
        migrations.RemoveField(
            model_name='premissa',
            name='tempo_vida_minima',
        ),
        migrations.RemoveField(
            model_name='premissa',
            name='validade_proposta_dias',
        ),
        migrations.AddField(
            model_name='premissa',
            name='inflacao_energetica_anual',
            field=models.DecimalField(decimal_places=2, default=10.0, help_text='%', max_digits=5),
        ),
        migrations.AddField(
            model_name='premissa',
            name='perda_eficiencia_anual',
            field=models.DecimalField(decimal_places=2, default=0.8, help_text='%', max_digits=5),
        ),
        migrations.AddField(
            model_name='premissa',
            name='prazo_entrega_padrao',
            field=models.IntegerField(default=45, help_text='Dias'),
        ),
        migrations.AddField(
            model_name='premissa',
            name='tarifa_energia_atual',
            field=models.DecimalField(decimal_places=2, default=1.05, help_text='R$/kWh', max_digits=6),
        ),
        migrations.AddField(
            model_name='premissa',
            name='taxas_maquininha',
            field=models.JSONField(default=dict, help_text="Ex: {'12': 12.5, '18': 18.3, '24': 25.0}"),
        ),
        migrations.AlterField(
            model_name='premissa',
            name='hsp_padrao',
            field=models.DecimalField(decimal_places=2, default=4.85, help_text='Horas de Sol Pleno', max_digits=5),
        ),
        migrations.AlterField(
            model_name='premissa',
            name='margem_lucro_percentual',
            field=models.DecimalField(decimal_places=2, default=30.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='premissa',
            name='overload_inversor',
            field=models.DecimalField(decimal_places=2, default=0.75, max_digits=5),
        ),
        migrations.AlterField(
            model_name='premissa',
            name='perda_padrao',
            field=models.DecimalField(decimal_places=2, default=0.2, help_text='Performance ratio', max_digits=5),
        ),
    ]
