# Generated by Django 5.0.1 on 2026-01-26 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('premissas', '0004_add_margem_desconto_avista'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='premissa',
            name='garantia_instalacao_meses',
        ),
        migrations.RemoveField(
            model_name='premissa',
            name='hsp_padrao',
        ),
        migrations.RemoveField(
            model_name='premissa',
            name='inflacao_energetica_anual',
        ),
        migrations.RemoveField(
            model_name='premissa',
            name='margem_desconto_avista_percentual',
        ),
        migrations.RemoveField(
            model_name='premissa',
            name='margem_deslocamento_percentual',
        ),
        migrations.RemoveField(
            model_name='premissa',
            name='overload_inversor',
        ),
        migrations.RemoveField(
            model_name='premissa',
            name='perda_eficiencia_anual',
        ),
        migrations.RemoveField(
            model_name='premissa',
            name='perda_padrao',
        ),
        migrations.RemoveField(
            model_name='premissa',
            name='prazo_entrega_padrao',
        ),
        migrations.RemoveField(
            model_name='premissa',
            name='tarifa_energia_atual',
        ),
        migrations.AlterField(
            model_name='premissa',
            name='cidade_empresa',
            field=models.CharField(default='Itaporã, MS', help_text='Cidade sede da empresa', max_length=200),
        ),
        migrations.AlterField(
            model_name='premissa',
            name='cidades_sem_cobranca',
            field=models.JSONField(default=list, help_text="Ex: ['Dourados', 'Itaporã']"),
        ),
        migrations.AlterField(
            model_name='premissa',
            name='comissao_percentual',
            field=models.DecimalField(decimal_places=2, default=5.0, help_text='% de comissão', max_digits=5),
        ),
        migrations.AlterField(
            model_name='premissa',
            name='consumo_veiculo_km_por_litro',
            field=models.DecimalField(decimal_places=2, default=10.0, help_text='Km por litro', max_digits=5),
        ),
        migrations.AlterField(
            model_name='premissa',
            name='imposto_percentual',
            field=models.DecimalField(decimal_places=2, default=6.0, help_text='% de imposto', max_digits=5),
        ),
        migrations.AlterField(
            model_name='premissa',
            name='margem_lucro_percentual',
            field=models.DecimalField(decimal_places=2, default=18.0, help_text='% de lucro', max_digits=5),
        ),
        migrations.AlterField(
            model_name='premissa',
            name='material_eletrico_faixas',
            field=models.JSONField(default=dict, help_text="Ex: {'3': 250, '5': 350, '8': 500}"),
        ),
        migrations.AlterField(
            model_name='premissa',
            name='montagem_por_painel',
            field=models.DecimalField(decimal_places=2, default=70, help_text='R$ por painel', max_digits=10),
        ),
        migrations.AlterField(
            model_name='premissa',
            name='preco_combustivel_litro',
            field=models.DecimalField(decimal_places=2, default=6.75, help_text='R$ por litro', max_digits=6),
        ),
        migrations.AlterField(
            model_name='premissa',
            name='taxas_maquininha',
            field=models.JSONField(default=dict, help_text="Ex: {'2': 2.5, '3': 3.5, '6': 5.0, '12': 8.0}"),
        ),
        migrations.AlterField(
            model_name='premissa',
            name='valor_projeto',
            field=models.DecimalField(decimal_places=2, default=400, help_text='R$ valor fixo', max_digits=10),
        ),
    ]
