# Generated by Django 5.0.1 on 2026-01-26 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('premissas', '0005_remove_premissa_garantia_instalacao_meses_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='premissa',
            name='margem_desconto_avista_percentual',
            field=models.DecimalField(decimal_places=2, default=2.0, help_text='% margem para desconto', max_digits=5),
        ),
        migrations.AlterField(
            model_name='premissa',
            name='cidades_sem_cobranca',
            field=models.JSONField(default=list, help_text='Cidades sem cobrança de deslocamento'),
        ),
        migrations.AlterField(
            model_name='premissa',
            name='material_eletrico_faixas',
            field=models.JSONField(default=dict, help_text='Faixas de potência em kWp'),
        ),
        migrations.AlterField(
            model_name='premissa',
            name='taxas_maquininha',
            field=models.JSONField(default=dict, help_text='Taxas por quantidade de parcelas'),
        ),
    ]
