# Generated by Django 5.0.1 on 2026-01-26 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('premissas', '0006_premissa_margem_desconto_avista_percentual_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='premissa',
            name='hsp_padrao',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Horas de Sol Pleno', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='premissa',
            name='overload_inversor',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Overload padrão', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='premissa',
            name='perda_padrao',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Performance ratio', max_digits=5, null=True),
        ),
    ]
