# Generated by Django 5.0.1 on 2026-02-10 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('premissas', '0007_premissa_hsp_padrao_premissa_overload_inversor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='premissa',
            name='hsp_padrao',
            field=models.DecimalField(decimal_places=2, default=5.5, help_text='Horas de Sol Pleno - Dourados/MS', max_digits=5),
        ),
        migrations.AlterField(
            model_name='premissa',
            name='perda_padrao',
            field=models.DecimalField(decimal_places=2, default=20.0, help_text='Perda do sistema (%)', max_digits=5),
        ),
    ]
