# Generated by Django 5.0.1 on 2026-02-10 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('premissas', '0008_alter_premissa_hsp_padrao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='premissa',
            name='inflacao_energetica_anual',
            field=models.DecimalField(decimal_places=2, default=8.0, help_text='% ao ano', max_digits=5),
        ),
        migrations.AddField(
            model_name='premissa',
            name='perda_eficiencia_anual',
            field=models.DecimalField(decimal_places=2, default=0.5, help_text='% ao ano', max_digits=5),
        ),
        migrations.AddField(
            model_name='premissa',
            name='tarifa_energia_atual',
            field=models.DecimalField(decimal_places=2, default=0.95, help_text='R$/kWh - Energisa MS', max_digits=6),
        ),
    ]
