# Generated by Django 5.0.1 on 2026-02-10 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('premissas', '0009_premissa_inflacao_energetica_anual_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='premissa',
            name='margem_deslocamento_percentual',
            field=models.DecimalField(decimal_places=2, default=20.0, help_text='% margem sobre custo', max_digits=5),
        ),
    ]
