# Generated by Django 5.0.1 on 2026-02-10 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('premissas', '0010_premissa_margem_deslocamento_percentual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='premissa',
            name='margem_deslocamento_percentual',
            field=models.DecimalField(decimal_places=2, default=20.0, help_text='% adicional repassado ao montador', max_digits=5),
        ),
    ]
