# Generated by Django 5.0.1 on 2026-01-23 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('vendedores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orcamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20, unique=True)),
                ('consumo_medio_kwh', models.DecimalField(decimal_places=2, max_digits=10)),
                ('geracao_requerida_kwh', models.DecimalField(decimal_places=2, max_digits=10)),
                ('potencia_instalada_kwp', models.DecimalField(decimal_places=2, max_digits=10)),
                ('potencia_placas_w', models.IntegerField()),
                ('quantidade_placas', models.IntegerField()),
                ('area_necessaria_m2', models.DecimalField(decimal_places=2, max_digits=10)),
                ('modelo_placa', models.CharField(max_length=255)),
                ('modelo_inversor', models.CharField(max_length=255)),
                ('quantidade_inversores', models.IntegerField(default=1)),
                ('custo_atual_energia', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('custo_com_sistema', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('economia_mensal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('economia_percentual', models.DecimalField(decimal_places=2, max_digits=5)),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_criacao', models.DateField(auto_now_add=True)),
                ('validade_dias', models.IntegerField(default=10)),
                ('pdf_gerado', models.FileField(blank=True, null=True, upload_to='orcamentos/')),
                ('convertido_proposta', models.BooleanField(default=False)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orcamentos', to='clientes.cliente')),
                ('vendedor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orcamentos', to='vendedores.vendedor')),
            ],
            options={
                'db_table': 'orcamentos',
                'ordering': ['-data_criacao'],
            },
        ),
    ]
