# Generated by Django 5.0.1 on 2026-01-26 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0002_cliente_vendedor'),
        ('vendedores', '0004_vendavendedor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orcamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20, unique=True)),
                ('nome_kit', models.CharField(max_length=255)),
                ('valor_kit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('marca_painel', models.CharField(max_length=100)),
                ('potencia_painel', models.IntegerField()),
                ('quantidade_paineis', models.IntegerField()),
                ('marca_inversor', models.CharField(max_length=100)),
                ('potencia_inversor', models.IntegerField()),
                ('quantidade_inversores', models.IntegerField(default=1)),
                ('tipo_estrutura', models.CharField(choices=[('ceramico', 'Cerâmico/Colonial'), ('fibromadeira', 'Fibromadeira'), ('fibrometal', 'Fibrometal'), ('zinco', 'Zinco'), ('solo', 'Solo'), ('laje', 'Laje')], max_length=20)),
                ('valor_estrutura', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('valor_material_eletrico', models.DecimalField(decimal_places=2, max_digits=10)),
                ('itens_adicionais', models.JSONField(default=list, help_text='[{categoria, item, qtd, valor_unit, valor_total}]')),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('forma_pagamento', models.CharField(default='avista', max_length=20)),
                ('taxa_juros', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('valor_final', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_parcela', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('data_criacao', models.DateField(auto_now_add=True)),
                ('validade_dias', models.IntegerField(default=10)),
                ('pdf_gerado', models.FileField(blank=True, null=True, upload_to='orcamentos/')),
                ('convertido_proposta', models.BooleanField(default=False)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orcamentos', to='clientes.cliente')),
                ('vendedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orcamentos', to='vendedores.vendedor')),
            ],
            options={
                'db_table': 'orcamentos',
                'ordering': ['-data_criacao'],
            },
        ),
    ]
